-- 코드를 작성해주세요

SELECT i1.ITEM_ID, i1.ITEM_NAME, i1.RARITY
FROM ITEM_INFO as i1
WHERE 
    i1.ITEM_ID NOT IN (
        SELECT PARENT_ITEM_ID
        FROM ITEM_TREE
        WHERE PARENT_ITEM_ID IS NOT NULL
    )
ORDER BY ITEM_ID DESC