-- 코드를 작성해주세요
-- SELECT t3.score, t2.EMP_NO , t2.EMP_NAME , t2.POSITION , t2.EMAIL
-- FROM HR_EMPLOYEES AS t2 , HR_GRADE AS t3

SELECT SUM(SCORE) AS SCORE , E.EMP_NO, E.EMP_NAME, E.POSITION , E.EMAIL
FROM HR_EMPLOYEES AS E
    INNER JOIN HR_GRADE AS G ON E.EMP_NO = G.EMP_NO
GROUP BY G.EMP_NO
ORDER BY 1 DESC
LIMIT 1
